export const HOMEOWNER_APIS = {
  nj: {
    label: 'NJ Statewide', state: 'NJ',
    base: 'https://data.nj.gov/resource/9ew9-4j5r.json',
    orderField: 'deed_date',
    normalize: (r) => ({
      id: (r.deed_book||'')+'_'+(r.deed_page||'')+(r.municipality||''),
      closeDate: r.deed_date||'', buyerName: r.grantee_name||'',
      sellerName: r.grantor_name||'',
      address: r.property_location||'', city: r.municipality||'',
      state: 'NJ', purchasePrice: parseFloat(r.consideration_amount)||0,
      source: 'NJ Property Transfers',
      sourceUrl: 'https://data.nj.gov/dataset/NJ-Property-Transfers/9ew9-4j5r',
    }),
  },
  tx_austin: {
    label: 'Austin TX', state: 'TX',
    base: 'https://data.austintexas.gov/resource/g5k8-8sud.json',
    orderField: 'close_date',
    normalize: (r) => ({
      id: r.id||r[':id']||'',
      closeDate: r.close_date||r.sale_date||'',
      buyerName: r.buyer||r.new_owner||'',
      sellerName: r.seller||r.prev_owner||'',
      address: r.address||r.property_address||'',
      city: 'Austin', state: 'TX',
      purchasePrice: parseFloat(r.purchase_price||r.sale_price)||0,
      source: 'Austin TX Property Sales',
      sourceUrl: 'https://data.austintexas.gov/dataset/Property-Sales/g5k8-8sud',
    }),
  },
  ca_la: {
    label: 'Los Angeles CA', state: 'CA',
    base: 'https://data.lacity.org/resource/8cyn-ky9g.json',
    orderField: 'document_date',
    normalize: (r) => ({
      id: r.document_number||r[':id']||'',
      closeDate: r.document_date||'',
      buyerName: r.grantee_name||'',
      sellerName: r.grantor_name||'',
      address: r.situs_address||r.property_address||'',
      city: r.city||'Los Angeles', state: 'CA',
      purchasePrice: parseFloat(r.consideration_amount||r.sale_price)||0,
      source: 'LA County Property Transfers',
      sourceUrl: 'https://data.lacity.org/dataset/LA-County-Property-Transfers/8cyn-ky9g',
    }),
  },
  ca_sf: {
    label: 'San Francisco CA', state: 'CA',
    base: 'https://data.sfgov.org/resource/wv7d-mcs4.json',
    orderField: 'document_date',
    normalize: (r) => ({
      id: r.document_number||r[':id']||'',
      closeDate: r.document_date||'',
      buyerName: r.grantee_names||r.grantee||'',
      sellerName: r.grantor_names||r.grantor||'',
      address: [(r.street_number||''),(r.street_name||''),(r.street_type||'')].filter(Boolean).join(' '),
      city: 'San Francisco', state: 'CA',
      purchasePrice: parseFloat(r.consideration_amount)||0,
      source: 'SF Property Transfers',
      sourceUrl: 'https://data.sfgov.org/dataset/SF-Property-Transfers/wv7d-mcs4',
    }),
  },
  il_cook: {
    label: 'Cook County IL', state: 'IL',
    base: 'https://datacatalog.cookcountyil.gov/resource/5pge-nu6u.json',
    orderField: 'deed_date',
    normalize: (r) => ({
      id: r.doc_number||r[':id']||'',
      closeDate: r.deed_date||r.sale_date||'',
      buyerName: r.buyer_name||r.grantee||'',
      sellerName: r.seller_name||r.grantor||'',
      address: r.property_address||r.address||'',
      city: r.city_name||r.municipality||'',
      state: 'IL',
      purchasePrice: parseFloat(r.sale_price||r.consideration_amount)||0,
      source: 'Cook County IL Property Sales',
      sourceUrl: 'https://datacatalog.cookcountyil.gov/dataset/Cook-County-Property-Sales/5pge-nu6u',
    }),
  },
  co_denver: {
    label: 'Denver CO', state: 'CO',
    base: 'https://www.denvergov.org/resource/property-sales.json',
    orderField: 'conveyance_date',
    normalize: (r) => ({
      id: r.reception_number||r[':id']||'',
      closeDate: r.conveyance_date||'',
      buyerName: r.buyer_name||r.grantee_name||'',
      sellerName: r.seller_name||r.grantor_name||'',
      address: r.property_address||r.situs_address||'',
      city: 'Denver', state: 'CO',
      purchasePrice: parseFloat(r.sale_price||r.consideration_amount)||0,
      source: 'Denver CO Property Sales',
      sourceUrl: 'https://www.denvergov.org/opendata/dataset/property-sales',
    }),
  },
  md: {
    label: 'Maryland Statewide', state: 'MD',
    base: 'https://opendata.maryland.gov/resource/ed4q-f8tm.json',
    orderField: 'deed_date',
    normalize: (r) => ({
      id: (r.liber||'')+'_'+(r.folio||''),
      closeDate: r.deed_date||'',
      buyerName: r.grantee_name||'',
      sellerName: r.grantor_name||'',
      address: r.property_location||r.address||'',
      city: r.city||r.municipality||'',
      state: 'MD',
      purchasePrice: parseFloat(r.consideration_amount)||0,
      source: 'MD Property Transfers',
      sourceUrl: 'https://opendata.maryland.gov/dataset/Maryland-Property-Transfers/ed4q-f8tm',
    }),
  },
};

export const PORTAL_SOURCES = [
  { key:'tx_harris', label:'Harris County TX', state:'TX', url:'https://hcad.org/property-search/real-property/', note:'Search HCAD for recent deed transfers' },
  { key:'nc_wake', label:'Wake County NC', state:'NC', url:'https://www.wakegov.com/departments-government/tax-administration/data-files-statistics-and-visualizations/real-estate-data', note:'Download real estate transfer data' },
  { key:'ks_sedgwick', label:'Sedgwick County KS', state:'KS', url:'https://www.sedgwickcounty.org/appraiser/property-search/', note:'Search recent property transfers' },
  { key:'az_maricopa', label:'Maricopa County AZ', state:'AZ', url:'https://mcassessor.maricopa.gov/', note:'Search Maricopa County Assessor' },
  { key:'az_pima', label:'Pima County AZ', state:'AZ', url:'https://www.assessor.pima.gov/', note:'Search Pima County Assessor' },
];
